# -*- coding: utf-8 -*-
"""British_airways_PPT_generation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cfqSUZ90CdwcfGB4G9ZTcwCZcHQ-yZYd
"""

! pip install python-pptx

!pip install --upgrade python-pptx

import pptx
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
from pptx.chart.data import CategoryChartData
# Import XL_CHART_TYPE from the correct module: pptx.enum.chart
from pptx.enum.chart import XL_CHART_TYPE
from pptx.enum.shapes import MSO_SHAPE

# Create a new PowerPoint presentation
prs = pptx.Presentation()

# Helper function to add text to a slide
def add_text_to_shape(shape, text, font_size=18, bold=False, color=(0, 0, 0)):
    text_frame = shape.text_frame
    text_frame.clear()
    p = text_frame.paragraphs[0]
    run = p.add_run()
    run.text = text
    font = run.font
    font.size = Pt(font_size)
    font.bold = bold
    font.color.rgb = RGBColor(*color)

# Helper function to add a bullet list
def add_bullet_list(slide, left, top, width, height, bullets, font_size=18):
    text_box = slide.shapes.add_textbox(left, top, width, height)
    text_frame = text_box.text_frame
    text_frame.word_wrap = True
    for bullet in bullets:
        p = text_frame.add_paragraph()
        p.text = bullet
        p.level = 0
        p.font.size = Pt(font_size)
        p.alignment = PP_ALIGN.LEFT

# Helper function to add a placeholder for an image
def add_image_placeholder(slide, left, top, width, height, image_path):
    text_box = slide.shapes.add_textbox(left, top, width, height)
    add_text_to_shape(text_box, f"Image Placeholder: {image_path}", font_size=14, color=(100, 100, 100))

# Slide 1: Title Slide
slide_layout = prs.slide_layouts[0]  # Title Slide
slide = prs.slides.add_slide(slide_layout)
title = slide.shapes.title
title.text = "A Data-Driven Customer Feedback Analysis for British Airways"
add_text_to_shape(title, title.text, font_size=40, bold=True)
subtitle = slide.placeholders[1]
subtitle.text = "Understanding Sentiment, Issues, and Opportunities\nPresented by [Your Name]\nGitHub: https://github.com/your-username/ba-analysis"
add_text_to_shape(subtitle, subtitle.text, font_size=20)
slide.notes_slide.notes_text_frame.text = "Introduce the analysis scope: customer sentiment, key issues, and strategic recommendations. Highlight the data-driven approach using scraped reviews."

# Slide 2: Sentiment Distribution
slide_layout = prs.slide_layouts[1]  # Title and Content
slide = prs.slides.add_slide(slide_layout)
title = slide.shapes.title
title.text = "Key Sentiment Analysis Findings"
add_text_to_shape(title, title.text, font_size=24, bold=True)
add_bullet_list(slide, Inches(0.5), Inches(1.5), Inches(4), Inches(4), [
    "51.8% Negative Reviews",
    "1.6% Neutral Feedback",
    "46.6% Positive Experiences",
    "Source: Scraped British Airways reviews"
])
# Add Pie Chart
chart_data = CategoryChartData()
chart_data.categories = ["Negative", "Neutral", "Positive"]
chart_data.add_series("Sentiment", (51.8, 1.6, 46.6))
chart = slide.shapes.add_chart(
    XL_CHART_TYPE.PIE, Inches(5), Inches(1.5), Inches(4), Inches(3), chart_data
).chart
chart.has_title = True
chart.chart_title.text_frame.text = "Customer Sentiment Distribution"
# Use notes_text_frame instead of text_frame for NotesSlide
slide.notes_slide.notes_text_frame.text = "Emphasize the polarized sentiment (near-equal positive/negative split). Note that neutral feedback is minimal, indicating strong opinions."

# Slide 3: Review Length Insights
slide_layout = prs.slide_layouts[1]
slide = prs.slides.add_slide(slide_layout)
title = slide.shapes.title
title.text = "Distribution of Review Lengths"
add_text_to_shape(title, title.text, font_size=24, bold=True) # Removed '抸txt'
add_bullet_list(slide, Inches(0.5), Inches(1.5), Inches(8), Inches(2), [
    "Most reviews: 50–150 words",
    "Some reviews: 600+ words"
])
add_image_placeholder(slide, Inches(0.5), Inches(3.5), Inches(8), Inches(4), "output/review_length_distribution.png")
# Use notes_text_frame instead of text_frame for NotesSlide
slide.notes_slide.notes_text_frame.text = "Highlight that concise reviews suggest quick feedback, while longer ones indicate detailed experiences or complaints. Connect review length to sentiment intensity (longer reviews often negative)."

# Slide 4: Word Frequency Overview
slide = prs.slides.add_slide(slide_layout)
title = slide.shapes.title
title.text = "Word Frequency Analysis"
add_text_to_shape(title, title.text, font_size=24, bold=True)
add_bullet_list(slide, Inches(0.5), Inches(1.5), Inches(8), Inches(2), [
    "Common words: flight, ba, trip, seat, service, delay, baggage, crew"
])
add_image_placeholder(slide, Inches(0.5), Inches(3.5), Inches(8), Inches(4), "output/review_wordcloud.png")
# Use notes_text_frame for NotesSlide
slide.notes_slide.notes_text_frame.text = "Explain that these words reflect critical touchpoints in the customer journey. Link to sentiment: Positive words (service, crew) vs. negative (delay, baggage)."

# Slide 5: Positive Sentiment Language
slide = prs.slides.add_slide(slide_layout)
title = slide.shapes.title
title.text = "Positive Reviews Word Cloud"
add_text_to_shape(title, title.text, font_size=24, bold=True)
add_bullet_list(slide, Inches(0.5), Inches(1.5), Inches(8), Inches(2), [
    "Praise for: seat, service, food, crew, suite",
    'Tone: "good," "excellent," "attendant," "pleasant"'
])
add_image_placeholder(slide, Inches(0.5), Inches(3.5), Inches(8), Inches(4), "output/wordcloud_positive.png")
# Use notes_text_frame for NotesSlide
slide.notes_slide.notes_text_frame.text = "Highlight strengths in in-flight experience (e.g., crew and food). Suggest leveraging these positives in marketing." # Changed 'text_frame' to 'notes_text_frame'

# Slide 6: Neutral Sentiment Language
slide = prs.slides.add_slide(slide_layout)
title = slide.shapes.title
title.text = "Neutral Reviews Word Cloud"
add_text_to_shape(title, title.text, font_size=24, bold=True)
add_bullet_list(slide, Inches(0.5), Inches(1.5), Inches(8), Inches(2), [
    "Mixed feedback: joke, four, class, attention, companion, business"
])
add_image_placeholder(slide, Inches(0.5), Inches(3.5), Inches(8), Inches(4), "output/wordcloud_neutral.png")
# Use notes_text_frame instead of text_frame for NotesSlide
slide.notes_slide.notes_text_frame.text = "Note ambiguity in neutral feedback, often tied to Business Class expectations. Suggest investigating inconsistencies in premium services." # Changed 'text_frame' to 'notes_text_frame'

# Slide 7: Negative Sentiment Language
slide = prs.slides.add_slide(slide_layout)
title = slide.shapes.title
title.text = "Negative Reviews Word Cloud"
add_text_to_shape(title, title.text, font_size=24, bold=True)
add_bullet_list(slide, Inches(0.5), Inches(1.5), Inches(8), Inches(2), [
    "Issues: crew, water, cabin, route",
    'Tone: "awful," "unhappy," "shame," "elderly," "delayed"'
])
add_image_placeholder(slide, Inches(0.5), Inches(3.5), Inches(8), Inches(4), "output/wordcloud_negative.png")
# Use notes_text_frame instead of text_frame for NotesSlide
slide.notes_slide.notes_text_frame.text = "Emphasize operational failures (delays, cabin issues) as key drivers of dissatisfaction. Connect to later slides on common issues." # Changed 'text_frame' to 'notes_text_frame'

# Slide 8: Top Words
slide = prs.slides.add_slide(slide_layout)
title = slide.shapes.title
title.text = "Top 20 Most Frequent Words"
add_text_to_shape(title, title.text, font_size=24, bold=True)
add_bullet_list(slide, Inches(0.5), Inches(1.5), Inches(8), Inches(2), [
    "Reflects flight-specific concerns and passenger experience"
])
add_image_placeholder(slide, Inches(0.5), Inches(3.5), Inches(8), Inches(4), "output/top20_words.png")
# Use notes_text_frame for NotesSlide
slide.notes_slide.notes_text_frame.text = "Highlight that frequent words align with both positive and negative sentiment. Use this to transition to issue-specific slides." # Changed text_frame to notes_text_frame

# Slide 9: Sentiment Trends Over Time
slide = prs.slides.add_slide(slide_layout)
title = slide.shapes.title
title.text = "Monthly Sentiment Trends (Oct 2019–Mar 2021)"
add_text_to_shape(title, title.text, font_size=24, bold=True)
add_bullet_list(slide, Inches(0.5), Inches(1.5), Inches(8), Inches(2), [
    "Peaks: Nov 2019 (68% positive), Jan 2020 (64.7% positive)",
    "Lows: Feb 2020 (21.4% positive), Sep 2020 (25% positive)",
    "Trend: Gradual improvement post-Sep 2020"
])
# Add Line Chart (simplified)
chart_data = CategoryChartData()
chart_data.categories = ["Oct 19", "Nov 19", "Feb 20", "Sep 20", "Mar 21"]
chart_data.add_series("Positive", (61.0, 68.0, 21.4, 25.0, 50.0))
chart_data.add_series("Negative", (36.6, 32.0, 71.4, 70.0, 46.0))
chart = slide.shapes.add_chart(
    XL_CHART_TYPE.LINE, Inches(0.5), Inches(3.5), Inches(8), Inches(4), chart_data
).chart
chart.has_title = True
chart.chart_title.text_frame.text = "Sentiment Trends"
# Use notes_text_frame instead of text_frame for NotesSlide
slide.notes_slide.notes_text_frame.text = "Discuss COVID-19’s impact on early 2020 sentiment. Note recovery trend as evidence of operational adjustments." # Changed 'text_frame' to 'notes_text_frame'

# Slide 10: Primary Customer Issues
slide = prs.slides.add_slide(slide_layout)
title = slide.shapes.title
title.text = "Common Issues Identified"
add_text_to_shape(title, title.text, font_size=24, bold=True)
add_bullet_list(slide, Inches(0.5), Inches(1.5), Inches(4), Inches(4), [
    "Flight Delays: 44.8% of complaints, ~2.5-hour average delay",
    "Baggage Handling: 26.4% of complaints, ~72-hour recovery time",
    "Customer Service: 36.2% of complaints, ~4.2-hour response time, 65% resolution rate"
])
# Add Bar Chart
chart_data = CategoryChartData()
chart_data.categories = ["Delays", "Baggage", "Service", "Other"]
chart_data.add_series("Issues", (44.8, 26.4, 36.2, 10.0))
chart = slide.shapes.add_chart(
    XL_CHART_TYPE.COLUMN_CLUSTERED, Inches(5), Inches(1.5), Inches(4), Inches(3), chart_data
).chart
chart.has_title = True
chart.chart_title.text_frame.text = "Issue Distribution"
# Use notes_text_frame for NotesSlide instead of text_frame
slide.notes_slide.notes_text_frame.text = "Emphasize delays as the top complaint, followed by service and baggage. Transition to recommendations for addressing these issues."

# Slide 11: Customer Service Response
slide = prs.slides.add_slide(slide_layout)
title = slide.shapes.title
title.text = "Customer Service Response Time"
add_text_to_shape(title, title.text, font_size=24, bold=True)
add_bullet_list(slide, Inches(0.5), Inches(1.5), Inches(8), Inches(2), [
    "Average resolution time: ~4.2 hours",
    "Frequent timeframes: 2 hours (36 mentions), 5 hours (28), 3 hours (25)"
])
# Add Flowchart (simplified as text boxes)
steps = [
    ("Submit Ticket", Inches(2), Inches(3)),
    ("Initial Response", Inches(2), Inches(4)),
    ("Review Issue", Inches(2), Inches(5)),
    ("Investigation", Inches(2), Inches(6)),
    ("Provide Solution", Inches(2), Inches(7)),
    ("Customer Feedback", Inches(2), Inches(8))
]
for step, x, y in steps:
    shape = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, x, y, Inches(2), Inches(0.5))
    add_text_to_shape(shape, step, font_size=14)
# Use notes_text_frame instead of text_frame for NotesSlide
slide.notes_slide.notes_text_frame.text = "Highlight slow response times as a pain point. Suggest automation or staffing improvements." # Changed 'text_frame' to 'notes_text_frame'

# Slide 12: Positive Feedback Highlights
slide = prs.slides.add_slide(slide_layout)
title = slide.shapes.title
title.text = "Positive Feedback Areas"
add_text_to_shape(title, title.text, font_size=24, bold=True)
add_bullet_list(slide, Inches(5), Inches(1.5), Inches(4), Inches(3), [
    "Staff: 53% of positive feedback",
    "Comfort: 46% appreciation",
    "Food: 45% consistent praise",
    "Entertainment: 14% mentions"
])
# Add Pie Chart
chart_data = CategoryChartData()
chart_data.categories = ["Staff", "Comfort", "Food", "Entertainment"]
chart_data.add_series("Feedback", (53, 46, 45, 14))
chart = slide.shapes.add_chart(
    XL_CHART_TYPE.PIE, Inches(0.5), Inches(1.5), Inches(4), Inches(3), chart_data
).chart
chart.has_title = True
chart.chart_title.text_frame.text = "Positive Feedback Distribution"
# Use notes_text_frame for NotesSlide instead of text_frame
slide.notes_slide.notes_text_frame.text = "Emphasize staff and comfort as key strengths. Note entertainment’s lower priority, suggesting minor investment needs." # Changed 'text_frame' to 'notes_text_frame'

# Slide 13: Strategic Recommendations
slide = prs.slides.add_slide(slide_layout)
title = slide.shapes.title
title.text = "Strategic Recommendations"
add_text_to_shape(title, title.text, font_size=24, bold=True)
add_bullet_list(slide, Inches(0.5), Inches(1.5), Inches(4), Inches(3), [
    "Quick Wins: Improve communication, enhance staff training",
    "Major Projects: Overhaul baggage system, optimize scheduling"
])
# Add Quadrant Chart (simplified as text)
add_bullet_list(slide, Inches(5), Inches(1.5), Inches(4), Inches(3), [
    "Staff Training: High Impact, Low Effort",
    "Baggage System: High Impact, High Effort",
    "Communication: Low Impact, Low Effort",
    "Scheduling: High Impact, Moderate Effort"
])
slide.notes_slide.notes_text_frame.text = "Highlight quick wins for immediate impact. Discuss long-term benefits of baggage and scheduling improvements."

# Slide 14: Regional Performance
slide = prs.slides.add_slide(slide_layout)
title = slide.shapes.title
title.text = "Regional Performance Analysis"
add_text_to_shape(title, title.text, font_size=24, bold=True)
add_bullet_list(slide, Inches(5), Inches(1.5), Inches(4), Inches(3), [
    "Europe: 87% of satisfaction",
    "Top Routes: London → New York, London → Singapore, London → Dubai",
    "Improvement Areas: Regional connectivity, holiday destinations, Business Class consistency"
])
# Add Pie Chart
chart_data = CategoryChartData()
chart_data.categories = ["Europe", "Other"]
chart_data.add_series("Satisfaction", (87, 13))
chart = slide.shapes.add_chart(
    XL_CHART_TYPE.PIE, Inches(0.5), Inches(1.5), Inches(4), Inches(3), chart_data
).chart
chart.has_title = True
chart.chart_title.text_frame.text = "Customer Satisfaction by Region"
# Use notes_text_frame instead of text_frame for NotesSlide
slide.notes_slide.notes_text_frame.text = "Highlight Europe’s strong performance as a benchmark. Discuss opportunities to improve non-European routes." # Changed 'text_frame' to 'notes_text_frame'

# Slide 15: Conclusion and Next Steps
slide = prs.slides.add_slide(slide_layout)
title = slide.shapes.title
title.text = "Thank You"
add_text_to_shape(title, title.text, font_size=24, bold=True)
add_bullet_list(slide, Inches(0.5), Inches(1.5), Inches(8), Inches(4), [
    "Summary: Mixed sentiment with pain points (delays, baggage, service) and strengths (staff, comfort, food)",
    "Next Steps: Monitor real-time feedback, standardize Business Class, enhance entertainment",
    "Call to Action: Visit GitHub repository (https://github.com/SoGhosh719/British_Airways)"
])
slide.notes_slide.notes_text_frame.text = "Recap key findings and actionable recommendations. Encourage audience to explore the GitHub repository for further details." # Use notes_text_frame for NotesSlide instead of text_frame

# Slide 16: Q&A
slide_layout = prs.slide_layouts[5]  # Blank
slide = prs.slides.add_slide(slide_layout)
title = slide.shapes.add_textbox(Inches(0.5), Inches(0.5), Inches(8), Inches(1))
add_text_to_shape(title, "Questions & Discussion", font_size=36, bold=True)
slide.notes_slide.notes_text_frame.text = "Be prepared to discuss real-time feedback analysis or route-specific data. Offer to generate additional visualizations if requested." # Changed 'text_frame' to 'notes_text_frame'

# Save the presentation
prs.save("British_Airways_Analysis.pptx")

# prompt: I need to download the presentation saved as
# prs.save("British_Airways_Analysis.pptx")

from google.colab import files
files.download("British_Airways_Analysis.pptx")